### ISSUE TITLE
Stable Rust

### ISSUE THREAD

**Issue by helgoboss** [Windfisch/rust-assert-no-alloc#5]
Thank you for this indispensable lib! I realized it doesn't build with stable Rust at the moment and the only reason seems to be the usage of the `external_doc` feature. Would you consider duplicating the README content instead of using `external_doc`?

**Comment by Windfisch** [comment]
Hey @helgoboss,
I greatly dislike the required copy-paste, but I see that this might make this crate significantly more useful.

Could you please check whether all is fine with stable rust now? I'd push the release to crates.io when you confirm that i did not forget any unstable-ism :). Feel free to reopen the issue if not.
